# Nivell 1

Des d’un Jupyter Notebook faràs els següents exercicis utilitzant la llibreria requests de Python.

Exploració bàsica amb una API de laboratori.

## 1.Consulta l’API pública JSONPlaceholder utilitzant el mètode GET per obtenir:

In [1]:
import requests
import pandas as pd

In [2]:
BASE_URL = 'https://jsonplaceholder.typicode.com'

## 2.Mostra per pantalla:

### La quantitat total de cada recurs.

### El codi d'estat de cada petició.

### Llista de publicacions (/posts)

In [4]:
res_posts = requests.get(f'{BASE_URL}/posts')
posts_data = res_posts.json()
posts_df = pd.DataFrame(posts_data)

In [6]:
display(f'Publicaciones:  {len(posts_df)}')
display(f'Codigo  de estado: {res_posts.status_code}')

'Publicaciones:  100'

'Codigo  de estado: 200'

### Llista d’usuaris (/users)

In [7]:
res_users = requests.get(f'{BASE_URL}/users')
users_data = res_users.json()
users_df = pd.DataFrame(users_data)

In [9]:
display(f'Usuarios: {len(users_df)}')
display(f'Users: Codigo de estado:{res_users.status_code}')

'Usuarios: 10'

'Users: Codigo de estado:200'

### Llista de tasques (/todos)

In [10]:
res_todos = requests.get(f'{BASE_URL}/todos')
todos_data = res_todos.json()
todos_df = pd.DataFrame(todos_data)

In [11]:
display(f'Cantidad de tareas: {len(todos_df)}')
display(f'Todos: Codi de estado:{res_todos.status_code}')

'Cantidad de tareas: 200'

'Todos: Codi de estado:200'

## 3 Fes una petició a una publicació inexistent per obtenir un error 404 i mostra el codi d'estat rebut.

In [15]:
res_404 = requests.get(f'{BASE_URL}/posts/9999')

In [16]:
print(f"Petició a /posts/9999:  Codigo de estado: {res_404.status_code}")

Petició a /posts/9999:  Codi d'estat: 404

## 4.Fes una petició POST per crear una nova publicació fictícia. Inclou el títol, el cos del missatge i un userId.

In [17]:
new_post = {
    'title': 'Sprint 10 - Ejecución de pruebas',
    'body': 'Esto es el cuerpo.',
    'userId': 1}

In [19]:
res_post = requests.post(f'{BASE_URL}/posts', json=new_post)

### Mostra la resposta JSON.

In [20]:
print(f'Respuesta JSON del servidor: {res_post.json()}')

Respuesta JSON del servidor: {'title': 'Sprint 10 - Ejecución de pruebas', 'body': 'Esto es el cuerpo.', 'userId': 1, 'id': 101}

### Mostra el codi d'estat.

In [25]:
print(f"Codi d'estat (POST): {res_post.status_code}")

Codi d'estat (POST): 201

## 5.Fes una petició PATCH per modificar parcialment una publicació existent.

In [27]:
datos_actualizados = {'title': 'Títol actualitzat amb mètode PATCH'}

In [28]:
res_patch = requests.patch(f'{BASE_URL}/posts/1', json=datos_actualizados)

### Mostra la resposta JSON i el codi d'estat.

In [34]:
print(f'Codigo de estado (PATCH): {res_patch.status_code}')
print(f'Respuesta JSON del servidor: {res_patch.json()}')

Codigo de estado (PATCH): 200
Respuesta JSON del servidor: {'userId': 1, 'id': 1, 'title': 'Títol actualitzat amb mètode PATCH', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}

## 6.Fes una petició DELETE sobre una publicació.

In [32]:
res_delete = requests.delete(f'{BASE_URL}/posts/1')

### Mostra la resposta JSON i el codi d'estat.

In [33]:
print(f'Codigo de estado (DELETE): {res_delete.status_code}')
print(f'Respuesta JSON del servidor: {res_delete.json()}')

Codigo de estado (DELETE): 200
Respuesta JSON del servidor: {}

# Nivell 2

Interacció amb una API pública real

## 1.Explora el repositori de Public APIs i tria una API que permeti fer peticions GET.

 **Open-Meteo Weather API**

  (https://open-meteo.com/)





### 3. Format de resposta:
- Confirmat que la resposta de tots els endpoints és en format **JSON**.

## 2.Llegeix la documentació de l'API:

### Revisa la secció d’endpoints disponibles. En un markdown, apunta com a mínim dos endpoints diferents.

### 1. Endpoints seleccionados:
- `/v1/forecast`: Obtenemos la predicción meteorológica (temperatura, lluvia, viento, etc...) para unas coordenadas geográficas concretas (latitud y longitud).
- `/v1/elevation`: Permite consultar la latitud sobre el nivel del mar para unas coordenadas determinadas.

### Comprova si ofereix filtres o paràmetres opcionals interessants. En un markdown, anota’ls.

### 2. Filtros y parámetros opcionales:
- `latitude` y `longitude` (Obligatorios): Coordenades geográficas de la localitzación a consultar.
- `hourly` (Opcional): Permite selecionar que variables horarias queremos recibir (p.e.: `temperature_2m`, `relative_humidity_2m`, `precipitation`).
- `timezone` (Opcional): Permite ajustar la zona horaria (p.e.: `auto` o `Europe/Madrid`).

### Verifica que la resposta sigui en format JSON (és el més adequat per a aquest exercici).

## 3.Fes una petició GET senzilla:

>>* URL:

In [35]:
url = 'https://api.open-meteo.com/v1/forecast'

>>* Parámetros para la ciudad de Barcelona:

In [36]:
parametro_bcn = {
    'latitude': 41.3887,
    'longitude': 2.1590,
    'hourly': ['temperature_2m', 'relative_humidity_2m'],
    'timezone': 'Europe/Madrid'}

>>* Petición:

In [37]:
response = requests.get(url, params = parametro_bcn)

### Mostra el codi d'estat de la resposta.

In [38]:
print(f'Codigo de estado HTTP: {response.status_code}')

Codigo de estado HTTP: 200

### Imprimeix de forma clara alguns dels camps de la resposta JSON.

In [39]:
data = response.json()

In [40]:
print(f'Latitud: {data['latitude']}')
print(f'Longitud: {data['longitude']}')
print(f'Elevación: {data['elevation']} metres')
print(f'Zona horaria: {data['timezone']}')

print('\nMustra de las 3 primeras horas de registro:')
for i in range(3):
    hora = data['hourly']['time'][i]
    temp = data['hourly']['temperature_2m'][i]
    humitat = data['hourly']['relative_humidity_2m'][i]
    print(f"- Fecha/Hora: {hora} | Temperatura: {temp}°C | Humedad: {humitat}%")

Latitud: 41.375
Longitud: 2.125
Elevación: 44.0 metres
Zona horaria: Europe/Madrid

Mustra de las 3 primeras horas de registro:
- Fecha/Hora: 2026-09-23T00:00 | Temperatura: 22.3°C | Humedad: 79%
- Fecha/Hora: 2026-09-23T01:00 | Temperatura: 21.9°C | Humedad: 82%
- Fecha/Hora: 2026-09-23T02:00 | Temperatura: 21.3°C | Humedad: 87%

## 4.Converteix les dades a un DataFrame de pandas:

>>* Extraemos el diccionario de datos horarios.

In [41]:
hourly_data = data['hourly']

>>* Convertimos el diccionario a un DataFrame.

In [42]:
df_meteo = pd.DataFrame(hourly_data)

>>* Convertimos la columna d etiempo a formato datetime de Pandas.

In [43]:
df_meteo['time'] = pd.to_datetime(df_meteo['time'])

### Mostra les primeres files del DataFrame.

In [44]:
df_meteo.head()

                 time  temperature_2m  relative_humidity_2m
0 2026-09-23 00:00:00            22.3                    79
1 2026-09-23 01:00:00            21.9                    82
2 2026-09-23 02:00:00            21.3                    87
3 2026-09-23 03:00:00            20.9                    88
4 2026-09-23 04:00:00            20.6                    89

# Nivell 3
API d'Open Data Barcelona

## 1.Utilitza l’API d’Open Data BCN per:

In [45]:
BASE_URL_BCN = 'https://opendata-ajuntament.barcelona.cat/data/api/action'

### Cercar un dataset del teu interès mitjançant package_search i package_show. .

Utilizamos package_search para buscar datasets de 'accidentes'

In [46]:
search_url = f'{BASE_URL_BCN}/package_search'
params_search = {'q': 'accidents'}

In [47]:
res_search = requests.get(search_url, params=params_search)
print(f'Codigo de estado (package_search): {res_search.status_code}')

Codigo de estado (package_search): 200

In [48]:
data_search = res_search.json()
datasets_trobats = data_search['result']['results']

## 2.Dels resultats obtinguts, selecciona’n un que tingui recursos disponibles en CSV o JSON.

Utilizamos *package_show* para ver los recursos disponibles del dataset.

In [49]:
dataset_id = datasets_trobats[0]['id']
print(f'Dataset seleccionat: {datasets_trobats[0]['title']} (ID: {dataset_id})')

Dataset seleccionat: Accidents by driver cause managed by the Guàrdia Urbana in the city of Barcelona (ID: 29d1b774-a83e-4c1e-91f7-1b9ad042ea83)

In [51]:
show_url = f'{BASE_URL_BCN}/package_show'
res_show = requests.get(show_url, params={'id': dataset_id})
print(f"Codigo de estado (package_show): {res_show.status_code}")

data_show = res_show.json()
resources = data_show['result']['resources']

Codigo de estado (package_show): 200

# Buscamos un recurso que este en formato CSV o JSON y que tenga el dataset activo.

In [52]:
selected_resource = None
for res in resources:
    if res.get('format', '').upper() in ['CSV', 'JSON'] and res.get('datastore_active'):
        selected_resource = res
        break

Si no en trobem cap amb datastore_active=True, seleccionem el primer que sigui CSV/JSON

In [54]:
if not selected_resource:
    for res in resources:
        if res.get('format', '').upper() in ['CSV', 'JSON']:
            selected_resource = res
            break

resource_id = selected_resource['id']
print(f'Nombre del recurso seleccionado: {selected_resource['name']}')
print(f'Formato: {selected_resource['format']}')
print(f'Resource ID: {resource_id}')

Nombre del recurso seleccionado: 2025_accidents_causa_conductor_gu_bcn.csv
Formato: CSV
Resource ID: 796504f6-7602-41a7-82a9-d3bd47e68dee

## 3.Amb el resource_id del recurs seleccionat, realitza una consulta mitjançant datastore_search per:

###Recuperar almenys 100 registres.

In [55]:
datastore_url = f'{BASE_URL_BCN}/datastore_search'
params_datastore = {
    'resource_id': resource_id,
    'limit': 100}

In [56]:
res_datastore = requests.get(datastore_url, params=params_datastore)
print(f'Codigo de estado (datastore_search): {res_datastore.status_code}')

Codigo de estado (datastore_search): 200

In [58]:
data_datastore = res_datastore.json()

Extraemos los registros

In [59]:
records = data_datastore['result']['records']
print(f'Número de registros recuperados: {len(records)}')

Número de registros recuperados: 100

## 4.Converteix els resultats a un DataFrame.

In [60]:
df_bcn = pd.DataFrame(records)

In [61]:
df_bcn.head()

,Codi_districte,Coordenada_UTM_X_ED50,Nk_Any,Causa conductor,Nom_districte,Descripcio_torn,Coordenada_UTM_Y_ED50,Codi_carrer,Nom_carrer,Dia_mes,...,Nom_barri,Hora_dia,Número_expedient,Latitud_WGS84,Codi_barri,Mes_any,_id,Num_postal,Longitud_WGS84,Descripcio_dia_setmana
0,1,430843.618,2025,No respectar distàncies,Ciutat Vella,Tarda,4580926.531,198804,Paral·lel,5,...,el Raval,14,2025S000065,41.37503971,1,1,1,48,2.17187632,Diumenge
1,1,430453.561,2025,Manca d'atenció a la conducció,Ciutat Vella,Nit,4581623.910,254803,Peu de la Creu,9,...,el Raval,23,2025S000133,41.38128717,1,1,2,,2.16713227,Dijous
2,1,430453.561,2025,No respectat pas de vianants,Ciutat Vella,Nit,4581623.910,254803,Peu de la Creu,9,...,el Raval,23,2025S000133,41.38128717,1,1,3,,2.16713227,Dijous
3,1,431179.015,2025,Manca precaució incorporació circulació,Ciutat Vella,Matí,4581196.729,34308,Rambla,10,...,el Raval,13,2025S000159,41.37750208,1,1,4,9,2.17585604,Divendres
4,1,430352.425,2025,Manca d'atenció a la conducció,Ciutat Vella,Tarda,4581614.925,368100,Guifré,15,...,el Raval,16,2025S000256,41.38119749,1,1,5,,2.16592388,Dimecres

## 5.Desa el DataFrame en un fitxer .csv.

In [62]:
nom_fitxer = 'opendata_bcn_resultats.csv'
df_bcn.to_csv(nom_fitxer, index=False, encoding='utf-8')